import React from 'react';
import { ArrowRight, Globe2, Handshake, PackageSearch, Ship, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';

const services = [
  { icon: PackageSearch, title: 'Global Sourcing', description: 'Finding the right source for the right requirement through product, quality, quantity and delivery-led sourcing.' },
  { icon: Ship, title: 'Import', description: 'Bringing global supply closer by helping businesses explore suppliers and international procurement opportunities.' },
  { icon: TrendingUp, title: 'Export', description: 'Taking products to new markets by connecting businesses with potential international buyers and opportunities.' },
  { icon: Handshake, title: 'International Trading', description: 'Connecting buyers, sellers and opportunities through thoughtful, relationship-driven trade facilitation.' },
];

const steps = [
  ['01', 'Understand', 'We begin with your product, quantity, destination and commercial requirements.'],
  ['02', 'Source', 'We identify and explore relevant sourcing and trading opportunities.'],
  ['03', 'Connect', 'We establish communication between suitable business parties.'],
  ['04', 'Coordinate', 'We facilitate discussions around product, commercial and trade requirements.'],
  ['05', 'Build the Relationship', 'We create dependable business relationships with potential for continued cooperation.'],
];

const RJEnterprises: React.FC = () => (
  <div className="min-h-screen bg-black text-white">
    <section className="relative isolate overflow-hidden border-b border-[#23404a]">
      <img src="/assets/shutterstock_1069102985-1920w.jpeg" alt="Global industrial trade" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-20 grayscale" />
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_78%_30%,rgba(214,31,39,0.28),transparent_35%),linear-gradient(115deg,#000000_20%,rgba(0,0,0,0.8),#000000)]" />
      <div className="mx-auto max-w-[1400px] px-4 py-28 lg:px-10 lg:py-40"><p className="mb-6 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.28em] text-[#d61f27]"><span className="h-px w-10 bg-[#d61f27]" />RJ Enterprises</p><h1 className="max-w-4xl text-5xl font-black leading-[0.95] tracking-tight sm:text-7xl lg:text-8xl">Connecting businesses<br /><span className="text-[#d61f27]">across borders.</span></h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-gray-300 sm:text-xl">Trade beyond borders. We connect businesses with products, suppliers and commercial opportunities across markets.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link to="/contact" className="inline-flex items-center justify-center gap-2 bg-[#d61f27] px-6 py-3 text-sm font-black uppercase tracking-wide text-white transition-colors hover:bg-[#a9121b]">Explore our services <ArrowRight size={17} /></Link><Link to="/contact" className="inline-flex items-center justify-center gap-2 border border-white/30 px-6 py-3 text-sm font-black uppercase tracking-wide transition-colors hover:border-[#d61f27] hover:text-[#d61f27]">Start a trade enquiry</Link></div></div>
    </section>

    <section className="mx-auto max-w-[1400px] px-4 py-24 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr] lg:gap-24"><div><p className="mb-4 text-xs font-bold uppercase tracking-[0.25em] text-[#d61f27]">About RJ Enterprises</p><h2 className="text-4xl font-black leading-tight sm:text-5xl">Your connection to global trade.</h2></div><div className="space-y-6 text-lg leading-relaxed text-gray-400"><p>International trade creates opportunities for businesses to access new products, suppliers and markets. RJ Enterprises works across the trading process by understanding business requirements, exploring sourcing opportunities and facilitating connections.</p><p>From global sourcing and import requirements to export opportunities and international trading, our objective is to make business more connected, accessible and relationship-driven.</p></div></div></section>

    <section className="border-y border-[#1d2d3d] bg-black"><div className="mx-auto max-w-[1400px] px-4 py-24 lg:px-10 lg:py-32"><div className="mb-12 flex items-end justify-between gap-6"><div><p className="mb-4 text-xs font-bold uppercase tracking-[0.25em] text-[#d61f27]">What we do</p><h2 className="text-4xl font-black sm:text-5xl">Our international trade services</h2></div><Globe2 className="hidden text-[#d61f27] sm:block" size={52} strokeWidth={1} /></div><div className="grid gap-4 md:grid-cols-2">{services.map(({ icon: Icon, title, description }) => <article key={title} className="rounded-sm border border-[#1d2d3d] bg-black p-8 transition-colors hover:border-[#ff3b30]/80 lg:p-10"><Icon className="mb-8 text-[#d61f27]" size={32} strokeWidth={1.5} /><h3 className="mb-4 text-2xl font-black">{title}</h3><p className="leading-relaxed text-gray-400">{description}</p><Link to="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-black uppercase tracking-wide text-[#d61f27] hover:text-white">Discuss this service <ArrowRight size={16} /></Link></article>)}</div></div></section>

    <section className="mx-auto max-w-[1400px] px-4 py-24 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-2 lg:gap-24"><div><p className="mb-4 text-xs font-bold uppercase tracking-[0.25em] text-[#d61f27]">Supply solutions</p><h2 className="text-4xl font-black leading-tight sm:text-5xl">From requirement to reliable supply.</h2><p className="mt-6 leading-relaxed text-gray-400">Every business has different sourcing requirements. We understand the exact need before exploring suitable products, suppliers and trading opportunities.</p><Link to="/contact" className="mt-8 inline-flex items-center gap-2 border-b border-[#d61f27] pb-2 text-sm font-black uppercase tracking-wide text-white hover:text-[#d61f27]">Tell us what you need <ArrowRight size={17} /></Link></div><div className="border-l border-[#23404a] pl-8 lg:pl-12"><p className="text-2xl font-black leading-snug">Requirement <span className="text-[#d61f27]">→</span> Sourcing <span className="text-[#d61f27]">→</span> Connection <span className="text-[#d61f27]">→</span> Negotiation <span className="text-[#d61f27]">→</span> Trade</p><p className="mt-8 leading-relaxed text-gray-400">We aim to create relationships that can develop beyond a single transaction, whether the need is regular supply or a specific sourcing opportunity.</p></div></div></section>

    <section className="border-y border-[#1d2d3d] bg-black"><div className="mx-auto max-w-[1400px] px-4 py-24 lg:px-10 lg:py-28"><div className="mb-14 max-w-2xl"><p className="mb-4 text-xs font-bold uppercase tracking-[0.25em] text-[#d61f27]">How we work</p><h2 className="text-4xl font-black sm:text-5xl">From business requirement to global opportunity.</h2></div><div className="grid gap-4 md:grid-cols-5">{steps.map(([number, title, description]) => <div key={number} className="rounded-sm border border-[#1d2d3d] bg-black p-5"><p className="text-sm font-black text-[#d61f27]">{number}</p><h3 className="mt-8 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-relaxed text-gray-400">{description}</p></div>)}</div></div></section>

    <section className="mx-auto max-w-[1400px] px-4 py-24 text-center lg:px-10 lg:py-32"><p className="mb-4 text-xs font-bold uppercase tracking-[0.25em] text-[#d61f27]">Global trade</p><h2 className="text-5xl font-black sm:text-7xl">People. Products. Possibilities.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-gray-400">A product creates an opportunity. A market creates demand. A trusted relationship brings them together.</p><p className="mt-8 text-sm font-black uppercase tracking-[0.2em] text-[#d61f27]">Global sourcing <span className="mx-2 text-gray-600">|</span> Trusted partnership <span className="mx-2 text-gray-600">|</span> Growing together</p><Link to="/contact" className="mt-10 inline-flex items-center gap-2 bg-white px-7 py-4 text-sm font-black uppercase tracking-wide text-[#071217] hover:bg-[#d61f27]">Build a trade connection <ArrowRight size={17} /></Link></section>
  </div>
);

export default RJEnterprises;
